# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store',
            name='chain',
        ),
        migrations.DeleteModel(
            name='Chain',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
