# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chain',
            old_name='founded_data',
            new_name='founded_date',
        ),
    ]
